"""
内容过滤器管理器
统一协调和管理各个专门的过滤器，提供统一的过滤接口

Author: Claude (Generated by Architecture Refactor)
Created: 2025-08-17
"""

import logging
import asyncio
from typing import Dict, Any, Optional, List, Tuple
from dataclasses import dataclass
import time

# 导入过滤器基础架构
from app.services.filters.base import BaseFilter, FilterContext, FilterResult, PipelineResult

# 导入具体的过滤器
from app.services.filters.text_content_filter import text_content_filter
from app.services.filters.media_content_filter import media_content_filter
from app.services.filters.semantic_content_filter import semantic_content_filter
from app.services.filters.structural_content_filter import structural_content_filter

logger = logging.getLogger(__name__)


@dataclass
class FilterManagerConfig:
    """过滤器管理器配置"""
    enable_early_stopping: bool = True          # 启用早停机制
    enable_parallel_processing: bool = False    # 启用并行处理（谨慎使用）
    filter_timeout: float = 30.0                # 单个过滤器超时时间（秒）
    pipeline_timeout: float = 60.0              # 整个管道超时时间（秒）
    enable_detailed_logging: bool = True        # 启用详细日志
    enable_performance_monitoring: bool = True  # 启用性能监控


class ContentFilterManager:
    """
    内容过滤器管理器
    统一管理和协调各个专门的过滤器
    """
    
    def __init__(self, config: Optional[FilterManagerConfig] = None):
        self.config = config or FilterManagerConfig()
        
        # 注册的过滤器列表（按优先级排序）
        self.filters: List[BaseFilter] = []
        
        # 性能统计
        self.stats = {
            'total_processed': 0,
            'total_filtered': 0,
            'total_processing_time_ms': 0.0,
            'avg_processing_time_ms': 0.0,
            'filter_stats': {}
        }
        
        # 初始化标志
        self.initialized = False
        
        # 注册默认过滤器
        self._register_default_filters()
    
    def _register_default_filters(self):
        """注册默认的过滤器"""
        # 按优先级顺序添加过滤器
        # 1. 媒体过滤器（最高优先级，因为可能有早停）
        self.filters.append(media_content_filter)
        
        # 2. 结构化过滤器（高优先级，快速检测格式化推广）
        self.filters.append(structural_content_filter)
        
        # 3. 语义过滤器（中等优先级，AI分析）
        self.filters.append(semantic_content_filter)
        
        # 4. 文本过滤器（低优先级，兜底规则）
        self.filters.append(text_content_filter)
        
        logger.info(f"注册了 {len(self.filters)} 个过滤器")
    
    async def initialize(self) -> bool:
        """初始化过滤器管理器"""
        if self.initialized:
            return True
        
        try:
            success_count = 0
            
            # 初始化所有过滤器
            for filter_instance in self.filters:
                try:
                    if await filter_instance.initialize():
                        success_count += 1
                        logger.info(f"过滤器 {filter_instance.name} 初始化成功")
                    else:
                        logger.warning(f"过滤器 {filter_instance.name} 初始化失败")
                except Exception as e:
                    logger.error(f"过滤器 {filter_instance.name} 初始化异常: {e}")
            
            # 初始化过滤器统计
            for filter_instance in self.filters:
                self.stats['filter_stats'][filter_instance.name] = {
                    'processed': 0,
                    'filtered': 0,
                    'avg_time_ms': 0.0,
                    'error_count': 0
                }
            
            self.initialized = True
            logger.info(f"过滤器管理器初始化完成: {success_count}/{len(self.filters)} 个过滤器成功")
            
            return success_count > 0  # 至少有一个过滤器成功初始化
            
        except Exception as e:
            logger.error(f"过滤器管理器初始化失败: {e}")
            return False
    
    async def filter_message(self, content: str, channel_id: str = None, message_obj: Any = None, 
                           media_files: List[str] = None) -> Tuple[bool, str, str, dict]:
        """
        过滤消息内容 - 主要入口方法
        
        Args:
            content: 消息内容
            channel_id: 频道ID
            message_obj: Telegram消息对象
            media_files: 媒体文件路径列表
            
        Returns:
            (是否广告, 过滤后内容, 过滤原因, 详细结果)
        """
        if not self.initialized:
            await self.initialize()
        
        start_time = time.time()
        
        try:
            # 构建过滤上下文
            context = FilterContext(
                channel_id=channel_id,
                message_type="text" if not media_files else "media"
            )
            
            # 添加元数据
            context.add_metadata('channel_id', channel_id)
            context.add_metadata('message_obj', message_obj)
            context.add_metadata('media_files', media_files or [])
            context.add_metadata('has_media', bool(media_files))
            
            # 执行过滤管道
            pipeline_result = await self._execute_filter_pipeline(content, context)
            
            # 更新统计信息
            self._update_stats(pipeline_result)
            
            # 提取结果
            is_ad = not pipeline_result.passed
            filtered_content = pipeline_result.final_content
            filter_reason = pipeline_result.overall_reason or ""
            
            # 构建详细结果
            detailed_result = {
                'pipeline_stats': {
                    'total_processing_time_ms': pipeline_result.total_processing_time_ms,
                    'applied_filters': pipeline_result.applied_filters,
                    'early_stopped_at': pipeline_result.early_stopped_at
                },
                'filter_results': {
                    name: {
                        'passed': result.passed,
                        'confidence': result.confidence,
                        'reason': result.reason,
                        'processing_time_ms': result.processing_time_ms,
                        'details': result.details
                    }
                    for name, result in pipeline_result.filter_results.items()
                }
            }
            
            if self.config.enable_detailed_logging:
                logger.info(f"消息过滤完成: 是否广告={is_ad}, 原长度={len(content)}, 过滤后长度={len(filtered_content)}, 耗时={pipeline_result.total_processing_time_ms:.1f}ms")
            
            return is_ad, filtered_content, filter_reason, detailed_result
            
        except Exception as e:
            logger.error(f"消息过滤失败: {e}")
            processing_time = (time.time() - start_time) * 1000
            return False, content, f"过滤异常: {str(e)}", {
                'error': str(e),
                'processing_time_ms': processing_time
            }
    
    async def _execute_filter_pipeline(self, content: str, context: FilterContext) -> PipelineResult:
        """
        执行过滤器管道
        
        Args:
            content: 待过滤内容
            context: 过滤上下文
            
        Returns:
            管道执行结果
        """
        start_time = time.time()
        current_content = content
        filter_results = {}
        applied_filters = []
        early_stopped_at = None
        overall_passed = True
        overall_reasons = []
        
        for filter_instance in self.filters:
            if not filter_instance.is_enabled():
                continue
            
            if not filter_instance.can_handle(current_content, context):
                continue
            
            try:
                # 执行过滤器（带超时）
                filter_result = await asyncio.wait_for(
                    filter_instance.filter(current_content, context),
                    timeout=self.config.filter_timeout
                )
                
                # 记录结果
                filter_results[filter_instance.name] = filter_result
                applied_filters.append(filter_instance.name)
                
                # 更新内容
                if filter_result.filtered_content != current_content:
                    current_content = filter_result.filtered_content
                
                # 检查是否被过滤
                if not filter_result.passed:
                    overall_passed = False
                    if filter_result.reason:
                        overall_reasons.append(filter_result.reason)
                
                # 检查是否需要早停
                if (self.config.enable_early_stopping and 
                    filter_result.should_early_stop and 
                    not filter_result.passed):
                    early_stopped_at = filter_instance.name
                    logger.info(f"过滤器管道早停于: {filter_instance.name}")
                    break
                
            except asyncio.TimeoutError:
                logger.warning(f"过滤器 {filter_instance.name} 执行超时")
                self.stats['filter_stats'][filter_instance.name]['error_count'] += 1
            except Exception as e:
                logger.error(f"过滤器 {filter_instance.name} 执行失败: {e}")
                self.stats['filter_stats'][filter_instance.name]['error_count'] += 1
        
        total_processing_time = (time.time() - start_time) * 1000
        
        return PipelineResult(
            final_content=current_content,
            passed=overall_passed,
            total_processing_time_ms=total_processing_time,
            filter_results=filter_results,
            overall_reason=" | ".join(overall_reasons) if overall_reasons else None,
            early_stopped_at=early_stopped_at,
            applied_filters=applied_filters
        )
    
    def _update_stats(self, pipeline_result: PipelineResult):
        """更新统计信息"""
        self.stats['total_processed'] += 1
        if not pipeline_result.passed:
            self.stats['total_filtered'] += 1
        
        self.stats['total_processing_time_ms'] += pipeline_result.total_processing_time_ms
        self.stats['avg_processing_time_ms'] = (
            self.stats['total_processing_time_ms'] / self.stats['total_processed']
        )
        
        # 更新各个过滤器的统计
        for filter_name, filter_result in pipeline_result.filter_results.items():
            if filter_name in self.stats['filter_stats']:
                filter_stats = self.stats['filter_stats'][filter_name]
                filter_stats['processed'] += 1
                if not filter_result.passed:
                    filter_stats['filtered'] += 1
                
                # 更新平均处理时间
                total_time = filter_stats['avg_time_ms'] * (filter_stats['processed'] - 1) + filter_result.processing_time_ms
                filter_stats['avg_time_ms'] = total_time / filter_stats['processed']
    
    def filter_message_sync(self, content: str, channel_id: str = None, message_obj: Any = None) -> Tuple[bool, str, str]:
        """
        同步版本的消息过滤方法（向后兼容）
        
        Args:
            content: 消息内容
            channel_id: 频道ID
            message_obj: Telegram消息对象
            
        Returns:
            (是否广告, 过滤后内容, 过滤原因)
        """
        try:
            # 运行异步方法
            is_ad, filtered_content, filter_reason, _ = asyncio.run(
                self.filter_message(content, channel_id, message_obj)
            )
            return is_ad, filtered_content, filter_reason
        except Exception as e:
            logger.error(f"同步过滤失败: {e}")
            return False, content, f"同步过滤异常: {str(e)}"
    
    def get_filter_status(self) -> Dict[str, Any]:
        """获取所有过滤器状态"""
        filter_status = {}
        
        for filter_instance in self.filters:
            status = {
                'name': filter_instance.name,
                'enabled': filter_instance.is_enabled(),
                'initialized': getattr(filter_instance, 'initialized', False),
                'stats': self.stats['filter_stats'].get(filter_instance.name, {})
            }
            
            # 获取特定过滤器的额外状态信息
            try:
                if hasattr(filter_instance, 'get_ai_status'):
                    status['ai_status'] = filter_instance.get_ai_status()
                elif hasattr(filter_instance, 'get_structural_status'):
                    status['structural_status'] = filter_instance.get_structural_status()
                elif hasattr(filter_instance, 'get_media_summary'):
                    status['media_status'] = {'ocr_available': getattr(filter_instance, '_ocr_service', None) is not None}
            except Exception as e:
                logger.debug(f"获取过滤器 {filter_instance.name} 额外状态失败: {e}")
            
            filter_status[filter_instance.name] = status
        
        return {
            'manager_initialized': self.initialized,
            'total_filters': len(self.filters),
            'enabled_filters': sum(1 for f in self.filters if f.is_enabled()),
            'config': {
                'enable_early_stopping': self.config.enable_early_stopping,
                'enable_parallel_processing': self.config.enable_parallel_processing,
                'filter_timeout': self.config.filter_timeout,
                'pipeline_timeout': self.config.pipeline_timeout
            },
            'overall_stats': {
                'total_processed': self.stats['total_processed'],
                'total_filtered': self.stats['total_filtered'],
                'filter_rate': self.stats['total_filtered'] / max(self.stats['total_processed'], 1),
                'avg_processing_time_ms': self.stats['avg_processing_time_ms']
            },
            'filters': filter_status
        }
    
    def get_performance_report(self) -> Dict[str, Any]:
        """获取性能报告"""
        return {
            'timestamp': time.time(),
            'overall_stats': self.stats,
            'filter_performance': {
                name: {
                    'efficiency': stats['filtered'] / max(stats['processed'], 1),
                    'avg_time_ms': stats['avg_time_ms'],
                    'error_rate': stats['error_count'] / max(stats['processed'], 1)
                }
                for name, stats in self.stats['filter_stats'].items()
            }
        }
    
    def reset_stats(self):
        """重置统计信息"""
        self.stats = {
            'total_processed': 0,
            'total_filtered': 0,
            'total_processing_time_ms': 0.0,
            'avg_processing_time_ms': 0.0,
            'filter_stats': {}
        }
        
        # 重置各个过滤器的统计
        for filter_instance in self.filters:
            self.stats['filter_stats'][filter_instance.name] = {
                'processed': 0,
                'filtered': 0,
                'avg_time_ms': 0.0,
                'error_count': 0
            }
        
        logger.info("过滤器管理器统计信息已重置")
    
    def enable_filter(self, filter_name: str):
        """启用指定过滤器"""
        for filter_instance in self.filters:
            if filter_instance.name == filter_name:
                filter_instance.enable()
                logger.info(f"过滤器 {filter_name} 已启用")
                return
        logger.warning(f"未找到过滤器: {filter_name}")
    
    def disable_filter(self, filter_name: str):
        """禁用指定过滤器"""
        for filter_instance in self.filters:
            if filter_instance.name == filter_name:
                filter_instance.disable()
                logger.info(f"过滤器 {filter_name} 已禁用")
                return
        logger.warning(f"未找到过滤器: {filter_name}")


# 创建全局实例
content_filter_manager = ContentFilterManager()