services:
  app:
    build: .
    container_name: telegram_bot_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./telegram_system.db
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
      - TZ=Asia/Shanghai
    depends_on:
      - redis
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./data:/app/data
      - ./telegram_system.db:/app/telegram_system.db
    restart: unless-stopped
    networks:
      - telegram_network

  redis:
    image: redis:7-alpine
    container_name: telegram_bot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - telegram_network
    command: redis-server --appendonly yes

  # 可选：PostgreSQL 数据库（如果需要）
  # postgres:
  #   image: postgres:15
  #   container_name: telegram_bot_postgres
  #   environment:
  #     POSTGRES_DB: telegram_system
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - telegram_network

networks:
  telegram_network:
    driver: bridge

volumes:
  redis_data:
  # postgres_data:
