version: '3.8'

services:
  app:
    build: .
    container_name: telegram_bot_app_dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./telegram_system.db
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=DEBUG
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - telegram_network
    command: python main.py

  redis:
    image: redis:7-alpine
    container_name: telegram_bot_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - telegram_network
    command: redis-server --appendonly yes

networks:
  telegram_network:
    driver: bridge

volumes:
  redis_data: 