#!/bin/bash

# 域名配置脚本
# 用法: ./setup_domain.sh your-domain.com [prod|dev]
# 示例: ./setup_domain.sh example.com prod

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 日志函数
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 帮助信息
show_help() {
    echo "域名配置脚本"
    echo
    echo "用法: $0 <域名> [环境]"
    echo
    echo "参数:"
    echo "  域名        要配置的域名 (如: example.com)"
    echo "  环境        prod|dev (默认: prod)"
    echo
    echo "示例:"
    echo "  $0 example.com          # 配置生产环境域名"
    echo "  $0 example.com prod     # 配置生产环境域名"
    echo "  $0 example.com dev      # 配置开发环境域名"
    echo
    echo "功能:"
    echo "  - 自动修改对应环境的nginx配置"
    echo "  - 备份原始配置文件"
    echo "  - Git提交配置更改"
    echo "  - 重启nginx服务"
    echo "  - 显示DNS配置提醒"
}

# 检查参数
if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_help
    exit 0
fi

DOMAIN=$1
ENVIRONMENT=${2:-prod}

# 验证域名格式
if ! [[ "$DOMAIN" =~ ^[a-zA-Z0-9][a-zA-Z0-9\.-]+[a-zA-Z0-9]\.[a-zA-Z]{2,}$ ]]; then
    log_error "域名格式不正确: $DOMAIN"
    echo "示例正确格式: example.com"
    exit 1
fi

# 验证环境参数
if [[ "$ENVIRONMENT" != "prod" && "$ENVIRONMENT" != "dev" ]]; then
    log_error "环境参数必须是 'prod' 或 'dev'"
    exit 1
fi

log_info "配置域名: $DOMAIN (环境: $ENVIRONMENT)"

# 检查是否在项目目录
if [ ! -d "nginx" ]; then
    log_error "请在项目根目录运行此脚本"
    exit 1
fi

# 确定要修改的配置文件
if [ "$ENVIRONMENT" = "prod" ]; then
    NGINX_CONFIG="nginx/prod.conf"
    COMPOSE_FILE="docker-compose.prod.yml"
    SERVICE_PREFIX=""
else
    NGINX_CONFIG="nginx/nginx.conf"
    COMPOSE_FILE="docker-compose.yml"
    SERVICE_PREFIX=""
fi

# 检查配置文件是否存在
if [ ! -f "$NGINX_CONFIG" ]; then
    log_error "配置文件不存在: $NGINX_CONFIG"
    exit 1
fi

# 备份原始配置
BACKUP_FILE="${NGINX_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"
log_info "备份原始配置到: $BACKUP_FILE"
cp "$NGINX_CONFIG" "$BACKUP_FILE"

# 更新nginx配置
log_info "更新Nginx配置文件: $NGINX_CONFIG"
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    sed -i '' "s/server_name [^;]*;/server_name $DOMAIN www.$DOMAIN;/" "$NGINX_CONFIG"
else
    # Linux
    sed -i "s/server_name [^;]*;/server_name $DOMAIN www.$DOMAIN;/" "$NGINX_CONFIG"
fi

# 验证配置更改
log_info "验证配置更改..."
if grep -q "$DOMAIN" "$NGINX_CONFIG"; then
    log_success "Nginx配置更新成功"
else
    log_error "Nginx配置更新失败"
    # 恢复备份
    cp "$BACKUP_FILE" "$NGINX_CONFIG"
    log_info "已恢复原始配置"
    exit 1
fi

# 显示配置变更
log_info "配置变更内容:"
echo "   server_name -> $DOMAIN www.$DOMAIN"

# 提交到Git
log_info "提交配置更改到Git..."
git add "$NGINX_CONFIG"

# 生成提交信息
COMMIT_MSG="🌐 配置域名: $DOMAIN ($ENVIRONMENT环境)

- 更新$NGINX_CONFIG server_name为$DOMAIN
- 备份文件: $BACKUP_FILE
- 环境: $ENVIRONMENT

Domain: $DOMAIN
Environment: $ENVIRONMENT
Generated by setup_domain.sh"

if git commit -m "$COMMIT_MSG"; then
    log_success "Git提交成功"
else
    log_warning "Git提交失败或无更改需要提交"
fi

# 询问是否推送到远程仓库
echo
read -p "是否推送到远程仓库？(y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    if git push origin main; then
        log_success "已推送到远程仓库"
    else
        log_warning "推送失败，请检查网络连接或权限"
    fi
fi

# 重启服务
echo
log_info "检查Docker服务状态..."
if docker ps | grep -q "telegram_bot_nginx"; then
    log_info "重启Nginx服务..."
    if docker compose -f "$COMPOSE_FILE" restart nginx; then
        log_success "Nginx服务重启成功"
        
        # 等待服务启动
        sleep 3
        
        # 验证服务
        if curl -f -s http://localhost/health > /dev/null 2>&1; then
            log_success "服务健康检查通过"
        else
            log_warning "健康检查失败，服务可能还在启动中"
        fi
    else
        log_error "Nginx服务重启失败"
    fi
else
    log_warning "Docker服务未运行，请手动启动："
    if [ "$ENVIRONMENT" = "prod" ]; then
        echo "  ./deploy.sh start"
    else
        echo "  docker compose up -d"
    fi
fi

# 显示配置结果
echo
echo "🎉 域名配置完成！"
echo
echo "==================== 配置信息 ===================="
echo "域名: $DOMAIN"
echo "环境: $ENVIRONMENT"
echo "配置文件: $NGINX_CONFIG"
echo "备份文件: $BACKUP_FILE"
echo
echo "访问地址:"
echo "  - Web界面: http://$DOMAIN/static/login.html"
echo "  - API接口: http://$DOMAIN/api/"
echo "  - 健康检查: http://$DOMAIN/health"
echo
if [ "$ENVIRONMENT" = "dev" ]; then
    echo "  - 开发端口: http://$DOMAIN:8080/static/login.html"
fi
echo
echo "==================== DNS配置提醒 ===================="
echo "请在您的域名服务商处添加以下DNS记录："
echo "  A记录: $DOMAIN → 您的服务器IP"
echo "  A记录: www.$DOMAIN → 您的服务器IP"
echo
echo "==================== SSL配置建议 ===================="
echo "如需HTTPS，建议使用以下方案之一："
echo "1. Cloudflare代理 (推荐)"
echo "   - 登录Cloudflare控制台"
echo "   - 开启橙色云朵图标(代理模式)"
echo "   - SSL/TLS设置选择'灵活'或'完全'"
echo
echo "2. 外部反向代理"
echo "   - 使用Nginx、Caddy或Traefik"
echo "   - 配置Let's Encrypt自动证书"
echo
echo "3. CDN服务"
echo "   - 阿里云CDN、腾讯云CDN等"
echo "   - 自动提供HTTPS加速"
echo "=================================================="
echo
log_success "配置完成！请确保DNS解析生效后访问上述地址。"