"""
媒体内容过滤器
专门处理图片、视频等媒体文件的内容检测，包括OCR文字提取和广告识别

Author: Claude (Generated by Architecture Refactor)
Created: 2025-08-17
"""

import logging
import asyncio
from typing import List, Dict, Any, Optional, Tuple
from .base import BaseFilter, FilterContext, FilterResult
import time

logger = logging.getLogger(__name__)


class MediaContentFilter(BaseFilter):
    """
    媒体内容过滤器
    处理图片、视频等媒体文件的内容检测和广告识别
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__("media_content_filter", config)
        
        # OCR服务实例
        self._ocr_service = None
        
        # 支持的图片格式
        self.supported_image_formats = ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp']
        
        # 支持的视频格式
        self.supported_video_formats = ['.mp4', '.avi', '.mov', '.mkv', '.webm']
        
        # 广告检测阈值
        self.ad_detection_threshold = self.config.get('ad_detection_threshold', 30.0)
        
        # 初始化OCR服务
        self._initialize_ocr_service()
        
        # 标记初始化完成
        self.initialized = True
    
    async def initialize(self) -> bool:
        """初始化过滤器"""
        try:
            self._initialize_ocr_service()
            
            if self._ocr_service:
                logger.info("媒体内容过滤器初始化成功，OCR服务已加载")
            else:
                logger.warning("媒体内容过滤器初始化：OCR服务不可用")
            
            self.initialized = True
            return True
        except Exception as e:
            logger.error(f"媒体内容过滤器初始化失败: {e}")
            return False
    
    def _initialize_ocr_service(self):
        """初始化OCR服务"""
        try:
            from app.services.ocr_service import ocr_service
            self._ocr_service = ocr_service
            logger.debug("OCR服务初始化成功")
        except ImportError as e:
            logger.warning(f"无法导入OCR服务: {e}")
            self._ocr_service = None
        except Exception as e:
            logger.error(f"OCR服务初始化失败: {e}")
            self._ocr_service = None
    
    def can_handle(self, content: str, context: FilterContext) -> bool:
        """判断是否可以处理该内容"""
        # 检查是否有媒体文件
        media_files = context.get_metadata('media_files', [])
        if not media_files:
            return False
        
        # 检查是否有支持的媒体格式
        for media_file in media_files:
            if self._is_supported_media(media_file):
                return True
        
        return False
    
    def _is_supported_media(self, file_path: str) -> bool:
        """检查是否是支持的媒体格式"""
        if not file_path:
            return False
        
        file_path_lower = file_path.lower()
        
        # 检查图片格式
        for ext in self.supported_image_formats:
            if file_path_lower.endswith(ext):
                return True
        
        # 检查视频格式
        for ext in self.supported_video_formats:
            if file_path_lower.endswith(ext):
                return True
        
        return False
    
    def _is_image_file(self, file_path: str) -> bool:
        """检查是否是图片文件"""
        if not file_path:
            return False
        
        file_path_lower = file_path.lower()
        return any(file_path_lower.endswith(ext) for ext in self.supported_image_formats)
    
    def _is_video_file(self, file_path: str) -> bool:
        """检查是否是视频文件"""
        if not file_path:
            return False
        
        file_path_lower = file_path.lower()
        return any(file_path_lower.endswith(ext) for ext in self.supported_video_formats)
    
    async def filter(self, content: str, context: FilterContext) -> FilterResult:
        """执行媒体内容过滤"""
        start_time = time.time()
        
        try:
            media_files = context.get_metadata('media_files', [])
            if not media_files:
                return FilterResult(
                    filtered_content=content,
                    passed=True,
                    processing_time_ms=0.0,
                    reason="无媒体文件",
                    confidence=0.0
                )
            
            # 分离图片和视频文件
            image_files = [f for f in media_files if self._is_image_file(f)]
            video_files = [f for f in media_files if self._is_video_file(f)]
            
            # 处理结果
            ocr_results = {}
            is_advertisement = False
            ad_confidence = 0.0
            ad_indicators = []
            filtered_content = content
            
            # 处理图片文件（OCR + 广告检测）
            if image_files and self._ocr_service:
                ocr_results = await self._process_images(image_files, content)
                
                # 检查是否检测到广告
                for file_path, result in ocr_results.items():
                    if result.get('error'):
                        continue
                    
                    file_ad_score = result.get('ad_score', 0)
                    file_ad_indicators = result.get('ad_indicators', [])
                    
                    if file_ad_score >= self.ad_detection_threshold:
                        is_advertisement = True
                        ad_confidence = max(ad_confidence, file_ad_score / 100.0)  # 转换为0-1范围
                        ad_indicators.extend(file_ad_indicators)
                    
                    # 如果检测到广告，可以选择清空内容或添加OCR文字
                    if file_ad_score >= self.ad_detection_threshold:
                        # 高分广告，清空内容
                        filtered_content = ""
                    else:
                        # 将OCR文字添加到内容中
                        texts = result.get('texts', [])
                        if texts:
                            ocr_text = ' '.join(texts)
                            if filtered_content.strip():
                                filtered_content = f"{filtered_content}\n\n[图片文字内容]\n{ocr_text}"
                            else:
                                filtered_content = f"[图片文字内容]\n{ocr_text}"
            
            # 处理视频文件（目前仅记录）
            if video_files:
                logger.info(f"检测到 {len(video_files)} 个视频文件，暂不处理")
            
            # 生成过滤原因
            reason = ""
            if is_advertisement:
                reason = f"图片广告内容(分数:{ad_confidence*100:.0f})"
            elif ocr_results:
                reason = f"OCR处理完成，提取 {sum(len(r.get('texts', [])) for r in ocr_results.values())} 条文字"
            
            processing_time = (time.time() - start_time) * 1000
            
            return FilterResult(
                filtered_content=filtered_content,
                passed=not is_advertisement,
                processing_time_ms=processing_time,
                reason=reason,
                confidence=ad_confidence,
                details={
                    'processed_images': len(image_files),
                    'processed_videos': len(video_files),
                    'ocr_results': ocr_results,
                    'ad_indicators': ad_indicators,
                    'ad_score': ad_confidence * 100
                },
                should_early_stop=is_advertisement  # 如果是广告，建议早停
            )
            
        except Exception as e:
            logger.error(f"媒体过滤器处理失败: {e}")
            processing_time = (time.time() - start_time) * 1000
            return FilterResult(
                filtered_content=content,
                passed=True,
                processing_time_ms=processing_time,
                reason=f"处理异常: {str(e)}",
                confidence=0.0
            )
    
    async def _process_images(self, image_files: List[str], content: str) -> Dict[str, Dict[str, Any]]:
        """
        处理图片文件，执行OCR和广告检测
        
        Args:
            image_files: 图片文件路径列表
            content: 原始文本内容
            
        Returns:
            OCR处理结果字典
        """
        if not self._ocr_service or not image_files:
            return {}
        
        try:
            logger.info(f"开始OCR处理 {len(image_files)} 个图片文件")
            
            # 批量处理图片
            ocr_results = await self._ocr_service.batch_extract_content(image_files)
            
            # 处理结果统计
            total_texts = 0
            total_qr_codes = 0
            
            for file_path, result in ocr_results.items():
                if result.get('error'):
                    logger.warning(f"OCR处理失败: {file_path} - {result['error']}")
                    continue
                
                texts = result.get('texts', [])
                qr_codes = result.get('qr_codes', [])
                ad_score = result.get('ad_score', 0)
                ad_indicators = result.get('ad_indicators', [])
                
                total_texts += len(texts)
                total_qr_codes += len(qr_codes)
                
                logger.debug(f"OCR结果 {file_path}: {len(texts)}条文字, {len(qr_codes)}个二维码, 广告分数:{ad_score}")
                
                # 记录广告检测结果
                if ad_score >= self.ad_detection_threshold:
                    logger.warning(f"检测到图片广告: {file_path}, 分数:{ad_score}, 指标:{ad_indicators}")
            
            logger.info(f"OCR处理完成: 提取{total_texts}条文字, {total_qr_codes}个二维码")
            return ocr_results
            
        except Exception as e:
            logger.error(f"图片处理失败: {e}")
            return {}
    
    def extract_text_from_media(self, media_files: List[str]) -> List[str]:
        """
        从媒体文件中提取文字（同步版本）
        
        Args:
            media_files: 媒体文件路径列表
            
        Returns:
            提取的文字列表
        """
        if not media_files or not self._ocr_service:
            return []
        
        try:
            # 只处理图片文件
            image_files = [f for f in media_files if self._is_image_file(f)]
            if not image_files:
                return []
            
            # 运行异步OCR处理
            import asyncio
            ocr_results = asyncio.run(self._ocr_service.batch_extract_content(image_files))
            
            # 收集所有文字
            all_texts = []
            for file_path, result in ocr_results.items():
                if result.get('error'):
                    continue
                texts = result.get('texts', [])
                all_texts.extend(texts)
            
            logger.info(f"从 {len(image_files)} 个图片中提取了 {len(all_texts)} 条文字")
            return all_texts
            
        except Exception as e:
            logger.error(f"媒体文字提取失败: {e}")
            return []
    
    def detect_ad_in_media(self, media_files: List[str]) -> Tuple[bool, float, List[str]]:
        """
        检测媒体文件中的广告内容（同步版本）
        
        Args:
            media_files: 媒体文件路径列表
            
        Returns:
            (是否广告, 置信度, 广告指标列表)
        """
        if not media_files or not self._ocr_service:
            return False, 0.0, []
        
        try:
            # 只处理图片文件
            image_files = [f for f in media_files if self._is_image_file(f)]
            if not image_files:
                return False, 0.0, []
            
            # 运行异步OCR处理
            import asyncio
            ocr_results = asyncio.run(self._ocr_service.batch_extract_content(image_files))
            
            # 分析广告检测结果
            max_ad_score = 0.0
            all_ad_indicators = []
            
            for file_path, result in ocr_results.items():
                if result.get('error'):
                    continue
                
                ad_score = result.get('ad_score', 0)
                ad_indicators = result.get('ad_indicators', [])
                
                max_ad_score = max(max_ad_score, ad_score)
                all_ad_indicators.extend(ad_indicators)
            
            is_ad = max_ad_score >= self.ad_detection_threshold
            confidence = max_ad_score / 100.0  # 转换为0-1范围
            
            if is_ad:
                logger.info(f"媒体广告检测: 是广告, 分数:{max_ad_score}, 指标:{all_ad_indicators}")
            
            return is_ad, confidence, all_ad_indicators
            
        except Exception as e:
            logger.error(f"媒体广告检测失败: {e}")
            return False, 0.0, []
    
    def get_media_summary(self, media_files: List[str]) -> Dict[str, Any]:
        """
        获取媒体文件摘要信息
        
        Args:
            media_files: 媒体文件路径列表
            
        Returns:
            媒体摘要信息
        """
        if not media_files:
            return {'total': 0, 'images': 0, 'videos': 0, 'other': 0}
        
        image_count = sum(1 for f in media_files if self._is_image_file(f))
        video_count = sum(1 for f in media_files if self._is_video_file(f))
        other_count = len(media_files) - image_count - video_count
        
        return {
            'total': len(media_files),
            'images': image_count,
            'videos': video_count,
            'other': other_count,
            'supported': image_count + video_count,
            'ocr_available': self._ocr_service is not None
        }
    
    async def cleanup(self):
        """清理资源"""
        # 如果需要清理OCR服务资源，可以在这里实现
        pass


# 创建全局实例
media_content_filter = MediaContentFilter()