"""
语义内容过滤器
专门处理基于AI的智能语义分析，包括尾部过滤、AI广告检测等

Author: Claude (Generated by Architecture Refactor)
Created: 2025-08-17
"""

import logging
import asyncio
from typing import Dict, Any, Optional, Tuple
from .base import BaseFilter, FilterContext, FilterResult
import time

logger = logging.getLogger(__name__)


class SemanticContentFilter(BaseFilter):
    """
    语义内容过滤器
    基于AI和语义分析的智能内容过滤
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__("semantic_content_filter", config)
        
        # AI服务实例
        self._ai_filter = None
        self._intelligent_tail_filter = None
        self._tail_filter_engine = None
        
        # 检测阈值
        self.ai_confidence_threshold = self.config.get('ai_confidence_threshold', 0.85)
        self.pure_ad_threshold = self.config.get('pure_ad_threshold', 0.95)
        
        # 初始化AI服务
        self._initialize_ai_services()
        
        # 标记初始化完成
        self.initialized = True
    
    async def initialize(self) -> bool:
        """初始化过滤器"""
        try:
            self._initialize_ai_services()
            
            available_services = []
            if self._ai_filter and getattr(self._ai_filter, 'initialized', False):
                available_services.append("AI广告检测")
            if self._intelligent_tail_filter:
                available_services.append("智能尾部过滤")
            if self._tail_filter_engine:
                available_services.append("尾部过滤引擎")
            
            if available_services:
                logger.info(f"语义内容过滤器初始化成功，可用服务: {', '.join(available_services)}")
            else:
                logger.warning("语义内容过滤器初始化：所有AI服务均不可用")
            
            self.initialized = True
            return True
        except Exception as e:
            logger.error(f"语义内容过滤器初始化失败: {e}")
            return False
    
    def _initialize_ai_services(self):
        """初始化AI相关服务"""
        # 初始化AI广告检测器
        try:
            from app.services.ai_filter import ai_filter
            self._ai_filter = ai_filter
            logger.debug("AI广告检测器初始化成功")
        except ImportError as e:
            logger.warning(f"无法导入AI广告检测器: {e}")
            self._ai_filter = None
        except Exception as e:
            logger.error(f"AI广告检测器初始化失败: {e}")
            self._ai_filter = None
        
        # 初始化智能尾部过滤器
        try:
            from app.services.intelligent_tail_filter import intelligent_tail_filter
            self._intelligent_tail_filter = intelligent_tail_filter
            logger.debug("智能尾部过滤器初始化成功")
        except ImportError as e:
            logger.warning(f"无法导入智能尾部过滤器: {e}")
            self._intelligent_tail_filter = None
        except Exception as e:
            logger.error(f"智能尾部过滤器初始化失败: {e}")
            self._intelligent_tail_filter = None
        
        # 初始化尾部过滤引擎
        try:
            from app.services.tail_filter_engine import TailFilterEngine
            self._tail_filter_engine = TailFilterEngine()
            logger.debug("尾部过滤引擎初始化成功")
        except ImportError as e:
            logger.warning(f"无法导入尾部过滤引擎: {e}")
            self._tail_filter_engine = None
        except Exception as e:
            logger.error(f"尾部过滤引擎初始化失败: {e}")
            self._tail_filter_engine = None
    
    def can_handle(self, content: str, context: FilterContext) -> bool:
        """判断是否可以处理该内容"""
        # 语义过滤器可以处理任何非空文本内容
        if not content or not isinstance(content, str):
            return False
        
        # 检查是否有可用的AI服务
        has_ai_service = (
            (self._ai_filter and getattr(self._ai_filter, 'initialized', False)) or
            self._intelligent_tail_filter or 
            self._tail_filter_engine
        )
        
        return has_ai_service and len(content.strip()) > 0
    
    async def filter(self, content: str, context: FilterContext) -> FilterResult:
        """执行语义内容过滤"""
        start_time = time.time()
        
        if not content:
            return FilterResult(
                filtered_content="",
                passed=True,
                processing_time_ms=0.0,
                reason="空内容",
                confidence=0.0
            )
        
        try:
            filtered_content = content
            is_advertisement = False
            confidence = 0.0
            reasons = []
            details = {}
            
            # 1. 智能尾部过滤（优先级最高）
            if self._intelligent_tail_filter:
                filtered_content, removed_tail, analysis = await self._apply_intelligent_tail_filter(
                    filtered_content, context
                )
                
                if len(filtered_content) < len(content):
                    reasons.append("智能尾部过滤")
                    confidence = max(confidence, analysis.get('confidence', 0.0) if analysis else 0.6)
                    details['intelligent_tail_filter'] = {
                        'removed_length': len(content) - len(filtered_content),
                        'removed_content': removed_tail,
                        'analysis': analysis
                    }
            
            # 2. 尾部过滤引擎（降级方案）
            elif self._tail_filter_engine:
                semantic_result = await self._apply_tail_filter_engine(filtered_content, context)
                if semantic_result['was_filtered']:
                    filtered_content = semantic_result['filtered_content']
                    reasons.append("语义尾部过滤")
                    confidence = max(confidence, 0.7)
                    details['semantic_tail_filter'] = semantic_result
            
            # 3. AI广告检测
            if self._ai_filter and getattr(self._ai_filter, 'initialized', False):
                ai_result = self._apply_ai_detection(filtered_content)
                if ai_result['is_ad'] and ai_result['confidence'] > self.ai_confidence_threshold:
                    is_advertisement = True
                    reasons.append(f"AI检测(置信度:{ai_result['confidence']:.2f})")
                    confidence = max(confidence, ai_result['confidence'])
                    
                    # 如果整条消息都是广告，清空内容
                    if ai_result['confidence'] > self.pure_ad_threshold:
                        filtered_content = ""
                        reasons.append("纯广告内容")
                
                details['ai_detection'] = ai_result
            
            # 4. 纯广告检测
            if not is_advertisement:
                pure_ad_result = self._detect_pure_advertisement(content, filtered_content)
                if pure_ad_result['is_pure_ad']:
                    is_advertisement = True
                    reasons.append("内容过滤比例过高")
                    confidence = max(confidence, pure_ad_result['confidence'])
                    details['pure_ad_detection'] = pure_ad_result
            
            # 生成过滤原因
            reason = " | ".join(reasons) if reasons else ""
            
            processing_time = (time.time() - start_time) * 1000
            
            return FilterResult(
                filtered_content=filtered_content,
                passed=not is_advertisement,
                processing_time_ms=processing_time,
                reason=reason,
                confidence=confidence,
                details=details,
                should_early_stop=is_advertisement and confidence > 0.9  # 高置信度广告建议早停
            )
            
        except Exception as e:
            logger.error(f"语义过滤器处理失败: {e}")
            processing_time = (time.time() - start_time) * 1000
            return FilterResult(
                filtered_content=content,
                passed=True,
                processing_time_ms=processing_time,
                reason=f"处理异常: {str(e)}",
                confidence=0.0
            )
    
    async def _apply_intelligent_tail_filter(self, content: str, context: FilterContext) -> Tuple[str, str, Optional[Dict]]:
        """
        应用智能尾部过滤
        
        Returns:
            (过滤后内容, 移除的尾部, 分析结果)
        """
        if not self._intelligent_tail_filter:
            return content, "", None
        
        try:
            # 构建上下文信息
            filter_context = {}
            channel_id = context.get_metadata('channel_id')
            if channel_id:
                filter_context['channel_id'] = channel_id
            
            has_media = context.get_metadata('has_media', False)
            if has_media:
                filter_context['has_media'] = has_media
            
            logger.debug(f"🎯 开始智能尾部过滤 - 输入内容长度: {len(content)}")
            
            # 使用智能尾部过滤器进行分析和过滤
            filtered_content, removed_tail, analysis = await self._intelligent_tail_filter.filter_message(
                content, filter_context
            )
            
            logger.debug(f"📋 智能尾部过滤结果: 输出长度={len(filtered_content)}")
            
            # 检查是否有内容被过滤
            if len(filtered_content) < len(content):
                logger.info(f"✅ 智能尾部过滤成功: {len(content)} -> {len(filtered_content)} 字符")
                
                if removed_tail:
                    logger.debug(f"🗑️ 移除的尾部内容: {removed_tail[:100]}...")
                
                if analysis:
                    logger.debug(f"📊 分析详情: 置信度={analysis.get('confidence', 0):.2f}")
                    if analysis.get('similar_samples'):
                        similar_count = len(analysis['similar_samples'])
                        logger.debug(f"🔍 找到 {similar_count} 个相似样本")
                    if analysis.get('filter_reason'):
                        logger.debug(f"🎯 过滤原因: {analysis['filter_reason']}")
            
            return filtered_content, removed_tail or "", analysis
            
        except Exception as e:
            logger.error(f"智能尾部过滤失败: {e}")
            return content, "", None
    
    async def _apply_tail_filter_engine(self, content: str, context: FilterContext) -> Dict[str, Any]:
        """
        应用尾部过滤引擎
        
        Returns:
            过滤结果字典
        """
        if not self._tail_filter_engine:
            return {
                'filtered_content': content,
                'was_filtered': False,
                'removed_tail': "",
                'analysis': None
            }
        
        try:
            has_media = context.get_metadata('has_media', False)
            
            logger.debug(f"🔄 降级到尾部过滤引擎")
            
            filtered_content, was_filtered, removed_tail, analysis = self._tail_filter_engine.filter_message(
                content, has_media
            )
            
            if was_filtered:
                logger.info(f"✅ 传统语义过滤成功: {len(content)} -> {len(filtered_content)} 字符")
            
            return {
                'filtered_content': filtered_content,
                'was_filtered': was_filtered,
                'removed_tail': removed_tail or "",
                'analysis': analysis
            }
            
        except Exception as e:
            logger.error(f"传统语义过滤失败: {e}")
            return {
                'filtered_content': content,
                'was_filtered': False,
                'removed_tail': "",
                'analysis': None
            }
    
    def _apply_ai_detection(self, content: str) -> Dict[str, Any]:
        """
        应用AI广告检测
        
        Returns:
            AI检测结果字典
        """
        if not self._ai_filter or not getattr(self._ai_filter, 'initialized', False):
            return {
                'is_ad': False,
                'confidence': 0.0,
                'available': False
            }
        
        try:
            is_ad, confidence = self._ai_filter.is_advertisement(content)
            
            logger.debug(f"🤖 AI广告检测: {'是' if is_ad else '否'}, 置信度: {confidence:.2f}")
            
            return {
                'is_ad': is_ad,
                'confidence': confidence,
                'available': True,
                'threshold_used': self.ai_confidence_threshold
            }
            
        except Exception as e:
            logger.error(f"AI广告检测失败: {e}")
            return {
                'is_ad': False,
                'confidence': 0.0,
                'available': False,
                'error': str(e)
            }
    
    def _detect_pure_advertisement(self, original_content: str, filtered_content: str) -> Dict[str, Any]:
        """
        检测是否为纯广告内容
        
        Returns:
            纯广告检测结果字典
        """
        if not original_content:
            return {
                'is_pure_ad': False,
                'confidence': 0.0,
                'compression_ratio': 1.0
            }
        
        # 计算压缩比例
        compression_ratio = len(filtered_content) / len(original_content)
        
        # 如果过滤后内容为空或者剩余内容太少，认为是纯广告
        is_pure_ad = False
        confidence = 0.0
        
        if not filtered_content.strip():
            is_pure_ad = True
            confidence = 0.95
        elif compression_ratio < 0.2:  # 过滤掉了80%以上的内容
            is_pure_ad = True
            confidence = 0.8 + (0.2 - compression_ratio) * 2.5  # 压缩比例越低，置信度越高
        
        logger.debug(f"📊 纯广告检测: {'是' if is_pure_ad else '否'}, 压缩比例: {compression_ratio:.2f}, 置信度: {confidence:.2f}")
        
        return {
            'is_pure_ad': is_pure_ad,
            'confidence': min(confidence, 1.0),
            'compression_ratio': compression_ratio,
            'original_length': len(original_content),
            'filtered_length': len(filtered_content)
        }
    
    async def is_pure_advertisement_ai(self, content: str) -> Tuple[bool, float]:
        """
        使用AI判断是否为广告内容（异步版本）
        
        Returns:
            (是否为广告, 置信度)
        """
        if not content:
            return False, 0.0
        
        try:
            # 尝试使用AI检测器
            if self._ai_filter and getattr(self._ai_filter, 'initialized', False):
                is_ad, confidence = self._ai_filter.is_advertisement(content)
                if confidence > 0.8:  # 高置信度时直接返回结果
                    logger.debug(f"AI广告检测: {'是' if is_ad else '否'}, 置信度: {confidence:.2f}")
                    return is_ad, confidence
                elif is_ad and confidence > 0.7:  # 中等置信度的广告也认为是广告
                    return True, confidence
        except Exception as e:
            logger.error(f"AI广告检测失败: {e}")
        
        # AI检测失败或置信度不足，回退到规则检测
        return self.is_pure_advertisement_rules(content)
    
    def is_pure_advertisement_rules(self, content: str) -> Tuple[bool, float]:
        """
        基于规则判断是否为纯广告内容
        
        Returns:
            (是否为广告, 置信度)
        """
        if not content:
            return False, 0.0
        
        # 创建虚拟上下文进行过滤测试
        context = FilterContext()
        
        # 模拟过滤过程
        try:
            # 这里需要一个简化的过滤逻辑，避免循环依赖
            # 可以使用文本过滤器进行基本检测
            from .text_content_filter import text_content_filter
            
            if text_content_filter.is_available():
                result = asyncio.run(text_content_filter.filter(content, context))
                compression_ratio = len(result.filtered_content) / max(len(content), 1)
                
                if compression_ratio < 0.2:
                    return True, 0.8
                elif not result.filtered_content.strip():
                    return True, 0.9
            
        except Exception as e:
            logger.debug(f"规则检测失败: {e}")
        
        return False, 0.0
    
    def get_ai_status(self) -> Dict[str, Any]:
        """获取AI服务状态"""
        return {
            'ai_filter_available': self._ai_filter is not None and getattr(self._ai_filter, 'initialized', False),
            'intelligent_tail_filter_available': self._intelligent_tail_filter is not None,
            'tail_filter_engine_available': self._tail_filter_engine is not None,
            'ai_confidence_threshold': self.ai_confidence_threshold,
            'pure_ad_threshold': self.pure_ad_threshold
        }


# 创建全局实例
semantic_content_filter = SemanticContentFilter()