"""
结构化内容过滤器
专门处理消息结构分析和格式化推广检测，包括按钮、实体、消息结构异常等

Author: Claude (Generated by Architecture Refactor)
Created: 2025-08-17
"""

import logging
from typing import Dict, Any, Optional, Tuple
from .base import BaseFilter, FilterContext, FilterResult
import time

logger = logging.getLogger(__name__)


class StructuralContentFilter(BaseFilter):
    """
    结构化内容过滤器
    基于消息结构和格式的推广内容检测
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__("structural_content_filter", config)
        
        # 结构分析服务
        self._message_structure_analyzer = None
        self._structural_ad_detector = None
        
        # 检测阈值
        self.structure_abnormality_threshold = self.config.get('structure_abnormality_threshold', 0.6)
        self.high_confidence_threshold = self.config.get('high_confidence_threshold', 0.8)
        
        # 初始化结构分析服务
        self._initialize_structural_services()
        
        # 标记初始化完成
        self.initialized = True
    
    async def initialize(self) -> bool:
        """初始化过滤器"""
        try:
            self._initialize_structural_services()
            
            available_services = []
            if self._message_structure_analyzer:
                available_services.append("消息结构分析")
            if self._structural_ad_detector:
                available_services.append("结构化广告检测")
            
            if available_services:
                logger.info(f"结构化内容过滤器初始化成功，可用服务: {', '.join(available_services)}")
            else:
                logger.warning("结构化内容过滤器初始化：所有结构分析服务均不可用")
            
            self.initialized = True
            return True
        except Exception as e:
            logger.error(f"结构化内容过滤器初始化失败: {e}")
            return False
    
    def _initialize_structural_services(self):
        """初始化结构分析相关服务"""
        # 初始化消息结构分析器
        try:
            from app.services.message_structure_analyzer import message_structure_analyzer
            self._message_structure_analyzer = message_structure_analyzer
            logger.debug("消息结构分析器初始化成功")
        except ImportError as e:
            logger.warning(f"无法导入消息结构分析器: {e}")
            self._message_structure_analyzer = None
        except Exception as e:
            logger.error(f"消息结构分析器初始化失败: {e}")
            self._message_structure_analyzer = None
        
        # 初始化结构化广告检测器
        try:
            from app.services.structural_ad_detector import structural_detector
            self._structural_ad_detector = structural_detector
            logger.debug("结构化广告检测器初始化成功")
        except ImportError as e:
            logger.warning(f"无法导入结构化广告检测器: {e}")
            self._structural_ad_detector = None
        except Exception as e:
            logger.error(f"结构化广告检测器初始化失败: {e}")
            self._structural_ad_detector = None
    
    def can_handle(self, content: str, context: FilterContext) -> bool:
        """判断是否可以处理该内容"""
        # 需要有消息对象或者足够的内容用于结构分析
        message_obj = context.get_metadata('message_obj')
        
        # 有消息对象时可以进行结构化检测
        if message_obj and self._structural_ad_detector:
            return True
        
        # 有足够内容时可以进行结构分析
        if content and len(content.strip()) > 10 and self._message_structure_analyzer:
            return True
        
        return False
    
    async def filter(self, content: str, context: FilterContext) -> FilterResult:
        """执行结构化内容过滤"""
        start_time = time.time()
        
        try:
            filtered_content = content
            is_advertisement = False
            confidence = 0.0
            reasons = []
            details = {}
            
            # 1. 消息结构分析（格式化推广检测）
            if content and self._message_structure_analyzer:
                structure_result = self._analyze_message_structure(content)
                if structure_result['is_structural_promo']:
                    is_advertisement = True
                    reasons.append(f"格式化推广({structure_result['detail_str']})")
                    confidence = max(confidence, structure_result['confidence'])
                    
                    # 高置信度时清空内容
                    if structure_result['total_score'] > self.high_confidence_threshold:
                        filtered_content = ""
                        reasons.append("高置信度格式化推广，内容已清空")
                    
                    details['structure_analysis'] = structure_result
            
            # 2. 结构化广告检测（检测按钮和实体中的广告）
            message_obj = context.get_metadata('message_obj')
            if message_obj and self._structural_ad_detector and not is_advertisement:
                structural_result = await self._detect_structural_ads(message_obj)
                if structural_result['has_structural_ad']:
                    is_advertisement = True
                    reasons.append(f"结构化广告({structural_result['ad_type']})")
                    confidence = max(confidence, 0.8)
                    
                    # 如果有需要清理的文本实体，更新内容
                    if structural_result.get('clean_text'):
                        filtered_content = structural_result['clean_text']
                    
                    details['structural_ad_detection'] = structural_result
            
            # 生成过滤原因
            reason = " | ".join(reasons) if reasons else ""
            
            processing_time = (time.time() - start_time) * 1000
            
            return FilterResult(
                filtered_content=filtered_content,
                passed=not is_advertisement,
                processing_time_ms=processing_time,
                reason=reason,
                confidence=confidence,
                details=details,
                should_early_stop=is_advertisement and confidence > 0.8  # 高置信度结构化广告建议早停
            )
            
        except Exception as e:
            logger.error(f"结构化过滤器处理失败: {e}")
            processing_time = (time.time() - start_time) * 1000
            return FilterResult(
                filtered_content=content,
                passed=True,
                processing_time_ms=processing_time,
                reason=f"处理异常: {str(e)}",
                confidence=0.0
            )
    
    def _analyze_message_structure(self, content: str) -> Dict[str, Any]:
        """
        分析消息结构
        
        Returns:
            结构分析结果字典
        """
        if not self._message_structure_analyzer:
            return {
                'is_structural_promo': False,
                'confidence': 0.0,
                'total_score': 0.0,
                'detail_str': "",
                'structure_scores': {},
                'available': False
            }
        
        try:
            is_structural_promo, structure_scores = self._message_structure_analyzer.analyze(content)
            
            # 详细的结构异常说明
            structure_details = []
            if structure_scores.get('emoji_density', 0) > 0.15:
                structure_details.append(f"表情密度{structure_scores['emoji_density']:.1%}")
            if structure_scores.get('link_density', 0) > 2.0:
                structure_details.append(f"链接密度{structure_scores['link_density']:.1f}/100字")
            if structure_scores.get('structure_abnormality', 0) > self.structure_abnormality_threshold:
                structure_details.append(f"结构异常{structure_scores['structure_abnormality']:.1%}")
            
            detail_str = ",".join(structure_details) if structure_details else f"综合得分{structure_scores.get('total_score', 0):.2f}"
            total_score = structure_scores.get('total_score', 0)
            confidence = min(total_score, 1.0)  # 确保置信度不超过1.0
            
            if is_structural_promo:
                logger.info(f"检测到格式化推广消息: {detail_str}")
            
            return {
                'is_structural_promo': is_structural_promo,
                'confidence': confidence,
                'total_score': total_score,
                'detail_str': detail_str,
                'structure_scores': structure_scores,
                'available': True
            }
            
        except Exception as e:
            logger.error(f"消息结构分析失败: {e}")
            return {
                'is_structural_promo': False,
                'confidence': 0.0,
                'total_score': 0.0,
                'detail_str': "",
                'structure_scores': {},
                'available': False,
                'error': str(e)
            }
    
    async def _detect_structural_ads(self, message_obj) -> Dict[str, Any]:
        """
        检测结构化广告（按钮、实体等）
        
        Returns:
            结构化广告检测结果字典
        """
        if not self._structural_ad_detector:
            return {
                'has_structural_ad': False,
                'ad_type': "",
                'clean_text': None,
                'available': False
            }
        
        try:
            structural_result = await self._structural_ad_detector.detect_structural_ads(message_obj)
            
            if structural_result['has_structural_ad']:
                logger.info(f"检测到结构化广告: {structural_result['ad_type']}")
            
            return {
                'has_structural_ad': structural_result['has_structural_ad'],
                'ad_type': structural_result.get('ad_type', ''),
                'clean_text': structural_result.get('clean_text'),
                'available': True,
                'details': structural_result.get('details', {})
            }
            
        except Exception as e:
            logger.error(f"结构化广告检测失败: {e}")
            return {
                'has_structural_ad': False,
                'ad_type': "",
                'clean_text': None,
                'available': False,
                'error': str(e)
            }
    
    def analyze_message_format(self, content: str) -> Dict[str, Any]:
        """
        分析消息格式特征（同步版本）
        
        Args:
            content: 消息内容
            
        Returns:
            格式分析结果
        """
        if not content:
            return {
                'emoji_count': 0,
                'link_count': 0,
                'line_count': 0,
                'avg_line_length': 0.0,
                'has_markdown_links': False,
                'has_special_chars': False
            }
        
        lines = content.split('\n')
        line_count = len(lines)
        non_empty_lines = [line for line in lines if line.strip()]
        avg_line_length = sum(len(line) for line in non_empty_lines) / max(len(non_empty_lines), 1)
        
        # 统计表情符号
        import re
        emoji_pattern = r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF\U00002600-\U000027BF]'
        emoji_count = len(re.findall(emoji_pattern, content))
        
        # 统计链接
        link_patterns = [
            r'https?://[^\s]+',
            r't\.me/[^\s]+',
            r'@[a-zA-Z][a-zA-Z0-9_]{4,31}'
        ]
        link_count = sum(len(re.findall(pattern, content, re.IGNORECASE)) for pattern in link_patterns)
        
        # 检测Markdown链接
        has_markdown_links = bool(re.search(r'\[[^\]]+\]\([^\)]+\)', content))
        
        # 检测特殊字符
        special_char_pattern = r'[📢📣🔔💬❤️🔗🔍✉️📮😍🇲🇲🔥✅👌]'
        has_special_chars = bool(re.search(special_char_pattern, content))
        
        return {
            'emoji_count': emoji_count,
            'link_count': link_count,
            'line_count': line_count,
            'avg_line_length': avg_line_length,
            'has_markdown_links': has_markdown_links,
            'has_special_chars': has_special_chars,
            'content_length': len(content),
            'emoji_density': emoji_count / max(len(content), 1),
            'link_density': link_count / max(len(content) / 100, 1)  # 每100字符的链接数
        }
    
    def is_formatted_promotion(self, content: str) -> Tuple[bool, float, Dict[str, Any]]:
        """
        判断是否为格式化推广内容（同步版本）
        
        Args:
            content: 消息内容
            
        Returns:
            (是否为格式化推广, 置信度, 详细分析)
        """
        if not content:
            return False, 0.0, {}
        
        try:
            # 使用结构分析器
            if self._message_structure_analyzer:
                is_promo, scores = self._message_structure_analyzer.analyze(content)
                confidence = scores.get('total_score', 0.0)
                return is_promo, confidence, scores
            else:
                # 降级到简单的格式分析
                format_analysis = self.analyze_message_format(content)
                
                # 简单的启发式规则
                score = 0.0
                if format_analysis['emoji_density'] > 0.1:
                    score += 0.3
                if format_analysis['link_density'] > 1.0:
                    score += 0.4
                if format_analysis['has_markdown_links']:
                    score += 0.2
                if format_analysis['has_special_chars']:
                    score += 0.1
                
                is_promo = score > 0.6
                return is_promo, score, format_analysis
                
        except Exception as e:
            logger.error(f"格式化推广检测失败: {e}")
            return False, 0.0, {'error': str(e)}
    
    def get_structural_status(self) -> Dict[str, Any]:
        """获取结构化服务状态"""
        return {
            'message_structure_analyzer_available': self._message_structure_analyzer is not None,
            'structural_ad_detector_available': self._structural_ad_detector is not None,
            'structure_abnormality_threshold': self.structure_abnormality_threshold,
            'high_confidence_threshold': self.high_confidence_threshold
        }


# 创建全局实例
structural_content_filter = StructuralContentFilter()